spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
          #url: ENC(9WbNc6dBlUIhDDYYpd+Wu7NjdhqXU6uA5bBAp8ncxFGnJZPBlUYCypXecMp+q2C3XIC1jHU9uzwJW88y3/nsN+fDltfCEDVABmmkq1748/NM1C5yXryMTVZYVFmnkIyNLKeEdqp9ZLOxsvkWq9JfmCuhwLn2BTRH)
          username: root
          #username: ENC(IgFr/mU3xwgIhR5JT8kc2g==)
          password: 123456
          # password: ENC(nyw0TDA85NsyA6NlqDz37A==)
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
  flyway:
    # 启用或禁用 flyway
    enabled: true
    baseline-on-migrate: true
    #    baseline-version: 1.0.2
    #数据库连接配置
    url: ${spring.datasource.dynamic.datasource.master.url}
    user: ${spring.datasource.dynamic.datasource.master.username}
    password: ${spring.datasource.dynamic.datasource.master.password}
    driver-class-name: ${spring.datasource.dynamic.datasource.master.driver-class-name}
    placeholder-replacement: false
    init-sqls:
      - CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
    # Flyway不严格验证版本顺序
    out-of-order: true
jwt:
  secret: common

shiro:
  loginUrl: /sso/login
  authorizedUrl: /*
  anonUrl: /swagger-resources/**
  sessionManager:
    #允许将sessionId 放到 cookie 中
    sessionIdCookieEnabled: true
    #允许将 sessionId 放到 Url 地址拦中
    sessionIdUrlRewritingEnabled: true
  web:
    #表示是否开启shiro
    enabled: true

server:
  port: 9095
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /common

knife4j:
  enable: true
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl